<a href="https://colab.research.google.com/github/Aisha1820/STUDENT-PERFORMANCE-PREDICTION-FOR-CAMPUS-PLACEMENT/blob/main/SPPCP_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r"/content/sample_data/roo_data.csv")

In [3]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])

38

In [4]:
dataset.iloc[:,14:38]

self-learning capability? Extra-courses did        certifications  \
0                           yes               yes     shell programming   
1                            no               yes      machine learning   
2                            no               yes       app development   
3                           yes                no                python   
4                            no                no       app development   
...                         ...               ...                   ...   
19995                        no                no       app development   
19996                        no                no            full stack   
19997                       yes               yes  information security   
19998                        no                no            full stack   
19999                       yes               yes       app development   

               workshops talenttests taken? olympiads  \
0        cloud computing                 no       yes   
1      database security                 no        no   
2       web technologies                 no       yes   
3           data science                yes        no   
4        cloud computing                 no        no   
...                  ...                ...       ...   
19995    cloud computing                yes        no   
19996   game development                 no       yes   
19997  database security                yes       yes   
19998    cloud computing                 no       yes   
19999  database security                 no       yes   

      reading and writing skills memory capability score  \
0                      excellent               excellent   
1                           poor                  medium   
2                           poor               excellent   
3                         medium               excellent   
4                           poor               excellent   
...                          ...                     ...   
19995                       poor               excellent   
19996                     medium               excellent   
19997                     medium               excellent   
19998                       poor                    poor   
19999                  excellent               excellent   

        interested career area  Job/Higher Studies?  ...  \
0              system developer       higherstudies  ...   
1      Business process analyst                 job  ...   
2                     developer       higherstudies  ...   
3                       testing       higherstudies  ...   
4                       testing       higherstudies  ...   
...                         ...                 ...  ...   
19995          system developer                 job  ...   
19996  Business process analyst       higherstudies  ...   
19997           cloud computing       higherstudies  ...   
19998                   testing                 job  ...   
19999                   testing                 job  ...   

      Salary Range Expected In a Realtionship? Gentle or Tuff behaviour?  \
0                    salary                 no                  stubborn   
1                    salary                yes                    gentle   
2                      Work                 no                  stubborn   
3                      Work                yes                    gentle   
4                    salary                 no                  stubborn   
...                     ...                ...                       ...   
19995                  Work                yes                  stubborn   
19996                salary                 no                  stubborn   
19997                  Work                yes                    gentle   
19998                  Work                 no                    gentle   
19999                  Work                 no                    gentle   

      Management or Technical Salary/work hard/smart worker  \
0 

In [5]:
dataset.iloc[:,:14]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  \
0                                      61                      9   
1                                      91                     12   
2                                      94                     11   
3                      

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
labelencoder = LabelEncoder()

In [8]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 8, 0, 0,
        1, 0, 0, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 0, 1, 5, 2,
        0, 0, 2, 1, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 0, 1, 0, 7,
        0, 1, 2, 0, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 1, 0, 6, 1, 1,
        0, 1, 0, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 2, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0]],
      dtype=object)

In [9]:
data[:5,14:]

array([[1, 1, 8, 0, 0, 1, 0, 0, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 0],
       [0, 1, 5, 2, 0, 0, 2, 1, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 1],
       [0, 1, 0, 7, 0, 1, 2, 0, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0],
       [1, 0, 6, 1, 1, 0, 1, 0, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1,
        1, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1,
        0, 0]], dtype=object)

In [10]:
from sklearn.preprocessing import Normalizer

In [11]:
data1=data[:,:14]

In [12]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [13]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [14]:
data2=data[:,14:]
data2.shape

(20000, 24)

In [15]:
df1 = np.append(normalized_data,data2,axis=1)

df1.shape

(20000, 38)

## adding headers

In [16]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [17]:
X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  ...  \
0                           0.252036              0.037186  ...   
1                            0.40831              0.053843  ...   
2                            0.39058              0.045706  ...   
3                           0.297812              0.030213  ...   
4                           0.315136              0.017268  ...   

  interested in games Interested Type of Books Salary Range Expected  \
0                   1                        0                     1   
1                   1                        1                     0   
2                   0                        0                     1   
3                   0                        1                     0   
4                   1                        0                     1   

  In a Realtionship? Gentle or Tuff behaviour? Management or Technical  \
0                  0                         0                       0   
1                  1                         0                       0   
2                  0                         1                       0   
3                  0                         1                       1   
4                  0                         1                       0   

  Salary/work hard/smart worker worked in teams ever? Introvert  
0           1                 0                     0         0  
1           0                 1                     0         1  
2           0                 1                     0         0  
3           1                 1                     0         0  
4           1                 1                     0         0  

[5 rows x 38 columns]

In [18]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [19]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

# Decision Tree Classifier 

In [20]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10) 

In [22]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [24]:
y_pred = clf.predict(X_test)

In [25]:
y_pred

array([24, 10, 15, ..., 14, 28,  7])

In [26]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [27]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*25*100)

confusion matrics= [[6 6 0 ... 4 2 2]
 [4 2 4 ... 5 3 4]
 [3 1 4 ... 5 2 4]
 ...
 [4 1 2 ... 5 3 5]
 [4 2 1 ... 9 6 5]
 [4 1 4 ... 5 3 4]]
  
accuracy= 76.875


# Decision tree with entropy

In [28]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [29]:
entropy_y_pred=clf_entropy.predict(X_test)

In [30]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [31]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [32]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*25*100)

confusion matrics= [[3 2 3 ... 0 2 5]
 [2 0 3 ... 4 3 3]
 [1 1 3 ... 2 3 2]
 ...
 [1 3 3 ... 4 7 1]
 [4 2 4 ... 4 2 2]
 [2 2 5 ... 5 1 2]]
  
accuracy= 71.25


# SVM (Support vector machine) classifier

In [33]:
from sklearn import svm

In [34]:
clf = svm.SVC()
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [35]:
svm_y_pred = clf.predict(X_test)

In [36]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [37]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*17*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 95.2


#  xgboost

# changing data type to int64

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10) 

In [39]:
X_train.shape

(14000, 38)

In [40]:
X_train=pd.to_numeric(X_train.values.flatten())

In [41]:
X_train=X_train.reshape((14000,38))

In [42]:
from xgboost import XGBClassifier

In [43]:
model = XGBClassifier()
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(objective='multi:softprob')

In [44]:
xgb_y_pred = clf.predict(X_test)

In [45]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)


In [46]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*17*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 97.75
